#!/bin/bash

echo "🚀 Backlog Chef POC - Step 4: Enrich with Context Demo"
echo "======================================================"
echo ""
echo "This demo shows how Step 4 enriches PBI candidates with context."
echo ""
echo "Prerequisites:"
echo "✅ TypeScript and Node.js installed"
echo "✅ Dependencies installed (npm install)"
echo "✅ Code built (npm run build)"
echo "✅ Input file from Step 3 exists"
echo ""
echo "Features Demonstrated:"
echo "• Semantic search for similar work"
echo "• Past decision discovery"
echo "• Technical documentation linking"
echo "• Risk identification"
echo "• Suggestion generation"
echo ""
echo "Mock Data Sources:"
echo "• DevOps: 7 historical PBIs"
echo "• Confluence: 6 technical documents"
echo "• Meetings: 6 transcripts with decisions"
echo ""
echo "To run the actual enrichment:"
echo "1. Copy .env.example to .env"
echo "2. Add your ANTHROPIC_API_KEY"
echo "3. Run: npm run enrich"
echo ""
echo "Example output available at:"
echo "output/example-enriched-pbis.json"
echo ""
echo "Run 'npm test' to verify the implementation."