/**
 * Step 8: Format Output
 *
 * Generates formatted output in multiple formats:
 * - HTML (interactive preview)
 * - Markdown (documentation)
 * - Azure DevOps (work item format)
 * - Confluence (wiki format)
 */

import { BaseStep } from './base-step';
import { PipelineContext } from '../types/pipeline-types';
import { ModelRouter } from '../../ai/router';

export class FormatOutputStep extends BaseStep {
  readonly name = 'format_output';
  readonly description = 'Generate formatted outputs (HTML, Markdown, DevOps, Confluence)';

  /**
   * Step can always execute (no prerequisites)
   */
  canExecute(context: PipelineContext): boolean {
    return context.readinessAssessed !== undefined;
  }

  /**
   * Execute output formatting
   */
  protected async executeStep(
    context: PipelineContext,
    router: ModelRouter
  ): Promise<PipelineContext> {
    console.log('  Generating formatted outputs...');

    // Output will be generated by the orchestrator
    // This step just marks that output formatting is complete

    console.log('  ✓ Output formatting ready');

    return context;
  }
}
