import { Formatter, PBIReadinessAssessment, ReadinessAssessmentInput } from '../types';

/**
 * Confluence Wiki Markup formatter
 * Outputs in Confluence storage format (wiki markup)
 */
export class ConfluenceFormatter implements Formatter {
  format(pbi: PBIReadinessAssessment): string {
    const sections: string[] = [];

    // Page Title and Header
    sections.push(`h1. ${pbi.pbi_id}: ${pbi.title}\n`);

    // Status Panel
    sections.push(this.createStatusPanel(pbi));
    sections.push('');

    // Blocking Issues Panel
    if (pbi.definition_of_ready_checklist.blocking_failures &&
        Object.keys(pbi.definition_of_ready_checklist.blocking_failures).length > 0) {
      sections.push(`{panel:title=🚨 BLOCKING ISSUES|borderStyle=solid|borderColor=#ff0000|titleBGColor=#ffcccc|bgColor=#fff5f5}`);
      sections.push(`Must resolve before sprint:\n`);

      let count = 1;
      for (const [criterionId, evaluation] of Object.entries(pbi.definition_of_ready_checklist.blocking_failures)) {
        const name = this.formatCriterionName(criterionId);
        sections.push(`*${count}. ${name}*`);

        if (evaluation.issues && evaluation.issues.length > 0) {
          for (const issue of evaluation.issues) {
            sections.push(`* ${issue}`);
          }
        }

        if (evaluation.action_required) {
          sections.push(`{quote}${evaluation.action_required}{quote}`);
        }
        count++;
      }

      sections.push(`{panel}`);
      sections.push('');
    }

    // Warnings Panel
    if (pbi.definition_of_ready_checklist.warnings &&
        Object.keys(pbi.definition_of_ready_checklist.warnings).length > 0) {
      sections.push(`{panel:title=⚠️ WARNINGS|borderStyle=solid|borderColor=#ff9900|titleBGColor=#fff3cd|bgColor=#fffef5}`);

      for (const [criterionId, evaluation] of Object.entries(pbi.definition_of_ready_checklist.warnings)) {
        const name = this.formatCriterionName(criterionId);
        sections.push(`* *${name}*`);

        if (evaluation.issue) {
          sections.push(`** Issue: ${evaluation.issue}`);
        }

        if (evaluation.recommendation) {
          sections.push(`** Recommendation: ${evaluation.recommendation}`);
        }
      }

      sections.push(`{panel}`);
      sections.push('');
    }

    // Immediate Actions
    if (pbi.recommended_next_actions.immediate && pbi.recommended_next_actions.immediate.length > 0) {
      sections.push(`h2. 📋 Immediate Actions\n`);
      sections.push(`||Priority||Action||Owner||Estimated Time||`);

      for (const action of pbi.recommended_next_actions.immediate) {
        const priority = action.priority;
        const owner = action.owner || '-';
        const time = action.estimated_time || '-';
        sections.push(`|${priority}|${action.action}|${owner}|${time}|`);
      }
      sections.push('');
    }

    // Before Sprint Actions
    if (pbi.recommended_next_actions.before_sprint && pbi.recommended_next_actions.before_sprint.length > 0) {
      sections.push(`h2. 📅 Before Sprint\n`);

      for (const action of pbi.recommended_next_actions.before_sprint) {
        sections.push(`* ${action.action}`);
        if (action.owner) {
          sections.push(`** Owner: ${action.owner}`);
        }
      }
      sections.push('');
    }

    // Estimation Guidance
    if (pbi.estimation_guidance) {
      sections.push(`h2. 📊 Estimation Guidance\n`);
      sections.push(`{info:title=Recommended Estimate}`);
      sections.push(`${pbi.estimation_guidance.recommended_estimate || 'Not estimated'}`);

      if (pbi.estimation_guidance.complexity_factors && pbi.estimation_guidance.complexity_factors.length > 0) {
        sections.push(`\n*Complexity Factors:*`);
        for (const factor of pbi.estimation_guidance.complexity_factors) {
          sections.push(`* ${factor}`);
        }
      }

      if (pbi.estimation_guidance.similar_work) {
        sections.push(`\n*Similar Work:* ${pbi.estimation_guidance.similar_work}`);
      }

      sections.push(`{info}`);
      sections.push('');
    }

    // Sprint Readiness Summary
    sections.push(`h2. 🎯 Sprint Readiness\n`);
    sections.push(`||Metric||Value||`);
    sections.push(`|ETA|${pbi.sprint_readiness_eta}|`);
    sections.push(`|Sprint Ready|${pbi.recommended_next_actions.sprint_ready ? '(/) Yes' : '(x) No'}|`);
    sections.push(`|Confidence|${pbi.confidence_in_eta}|`);

    if (pbi.recommended_next_actions.can_start) {
      sections.push(`|Can Start|${pbi.recommended_next_actions.can_start}|`);
    }
    sections.push('');

    // Page Footer
    sections.push(`----`);
    sections.push(`{note}Generated by Backlog Chef - Step 8: Final Output{note}`);

    return sections.join('\n');
  }

  formatSummary(input: ReadinessAssessmentInput): string {
    const sections: string[] = [];

    sections.push(`h1. 📊 Backlog Readiness Summary\n`);

    // Statistics Panel
    sections.push(`{panel:title=Summary Statistics|borderStyle=solid|borderColor=#0052cc|titleBGColor=#deebff|bgColor=#f4f5f7}`);
    sections.push(`* *Total PBIs Assessed:* ${input.metadata.total_pbis}`);
    sections.push(`* *Ready for Sprint:* ${input.metadata.ready_count} (${this.percentage(input.metadata.ready_count, input.metadata.total_pbis)}%)`);
    sections.push(`* *Needs Refinement:* ${input.metadata.needs_refinement_count}`);
    sections.push(`* *Not Ready:* ${input.metadata.not_ready_count}`);
    sections.push(`* *Average Readiness Score:* ${input.metadata.average_readiness_score}/100`);
    sections.push(`{panel}`);
    sections.push('');

    // PBI Table
    sections.push(`h2. PBI Breakdown\n`);
    sections.push(`||ID||Title||Status||Score||ETA||Confidence||`);

    for (const pbi of input.readiness_assessment) {
      const statusIcon = this.getStatusIcon(pbi.readiness_status);
      sections.push(`|${pbi.pbi_id}|${pbi.title}|${statusIcon}|${pbi.readiness_score}|${pbi.sprint_readiness_eta}|${pbi.confidence_in_eta}|`);
    }
    sections.push('');

    // Metadata
    sections.push(`h2. Metadata\n`);
    sections.push(`* *Generated:* ${new Date(input.metadata.generated_at).toLocaleString()}`);
    sections.push(`* *Model:* ${input.metadata.model_used}`);
    sections.push(`* *Processing Time:* ${(input.metadata.processing_duration_ms / 1000).toFixed(2)}s`);
    if (input.metadata.total_api_cost) {
      sections.push(`* *API Cost:* $${input.metadata.total_api_cost.toFixed(6)}`);
    }

    return sections.join('\n');
  }

  getFileExtension(): string {
    return '.txt';
  }

  getName(): string {
    return 'Confluence Wiki';
  }

  private createStatusPanel(pbi: PBIReadinessAssessment): string {
    let panelColor = '#ff0000'; // red for not ready
    let bgColor = '#fff5f5';

    if (pbi.readiness_status.includes('READY')) {
      panelColor = '#00aa00';
      bgColor = '#f0fff0';
    } else if (pbi.readiness_status.includes('NEEDS REFINEMENT')) {
      panelColor = '#ff9900';
      bgColor = '#fffef5';
    }

    const lines: string[] = [];
    lines.push(`{panel:title=Status|borderStyle=solid|borderColor=${panelColor}|titleBGColor=${bgColor}|bgColor=${bgColor}}`);
    lines.push(`* *Status:* ${pbi.readiness_status}`);
    lines.push(`* *Readiness Score:* ${pbi.readiness_score}`);
    lines.push(`* *Confidence:* ${pbi.confidence_in_eta}`);
    lines.push(`{panel}`);

    return lines.join('\n');
  }

  private getStatusIcon(status: string): string {
    if (status.includes('READY') && !status.includes('NOT')) {
      return '(/) READY';
    } else if (status.includes('NEEDS REFINEMENT')) {
      return '(!) NEEDS REFINEMENT';
    } else {
      return '(x) NOT READY';
    }
  }

  private formatCriterionName(id: string): string {
    return id
      .split('_')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  private percentage(value: number, total: number): number {
    return total > 0 ? Math.round((value / total) * 100) : 0;
  }
}
