import { Formatter, PBIReadinessAssessment, ReadinessAssessmentInput } from '../types';

/**
 * Markdown formatter for Obsidian and other Markdown-based tools
 */
export class MarkdownFormatter implements Formatter {
  format(pbi: PBIReadinessAssessment): string {
    const sections: string[] = [];

    // Header
    sections.push(`# ${pbi.pbi_id}: ${pbi.title}\n`);

    // Status and Score
    sections.push(`**Status**: ${pbi.readiness_status}`);
    sections.push(`**Readiness Score**: ${pbi.readiness_score}`);
    sections.push(`**Confidence**: ${pbi.confidence_in_eta}\n`);

    // Blocking Issues
    if (pbi.definition_of_ready_checklist.blocking_failures &&
        Object.keys(pbi.definition_of_ready_checklist.blocking_failures).length > 0) {
      sections.push(`## 🚨 BLOCKING ISSUES\n`);
      sections.push(`Must resolve before sprint:\n`);

      let blockingNumber = 1;
      for (const [criterionId, evaluation] of Object.entries(pbi.definition_of_ready_checklist.blocking_failures)) {
        const name = this.formatCriterionName(criterionId);
        sections.push(`${blockingNumber}. **${name}**`);

        if (evaluation.issues && evaluation.issues.length > 0) {
          for (const issue of evaluation.issues) {
            sections.push(`   - ${issue}`);
          }
        }

        if (evaluation.action_required) {
          sections.push(`   \n   **Action Required**:`);
          sections.push(`   ${evaluation.action_required.split('\n').join('\n   ')}\n`);
        }
        blockingNumber++;
      }
      sections.push('');
    }

    // Warnings
    if (pbi.definition_of_ready_checklist.warnings &&
        Object.keys(pbi.definition_of_ready_checklist.warnings).length > 0) {
      sections.push(`## ⚠️ WARNINGS\n`);

      for (const [criterionId, evaluation] of Object.entries(pbi.definition_of_ready_checklist.warnings)) {
        const name = this.formatCriterionName(criterionId);
        sections.push(`- **${name}**`);

        if (evaluation.issue) {
          sections.push(`  - ${evaluation.issue}`);
        }

        if (evaluation.recommendation) {
          sections.push(`  - Recommendation: ${evaluation.recommendation}`);
        }
      }
      sections.push('');
    }

    // Recommended Actions
    if (pbi.recommended_next_actions.immediate && pbi.recommended_next_actions.immediate.length > 0) {
      sections.push(`## 📋 IMMEDIATE ACTIONS\n`);

      for (const action of pbi.recommended_next_actions.immediate) {
        sections.push(`- [ ] **[${action.priority}]** ${action.action}`);
        if (action.owner) {
          sections.push(`  - Owner: ${action.owner}`);
        }
        if (action.estimated_time) {
          sections.push(`  - Estimated: ${action.estimated_time}`);
        }
      }
      sections.push('');
    }

    if (pbi.recommended_next_actions.before_sprint && pbi.recommended_next_actions.before_sprint.length > 0) {
      sections.push(`## 📅 BEFORE SPRINT\n`);

      for (const action of pbi.recommended_next_actions.before_sprint) {
        sections.push(`- [ ] ${action.action}`);
        if (action.owner) {
          sections.push(`  - Owner: ${action.owner}`);
        }
      }
      sections.push('');
    }

    // Estimation Guidance
    if (pbi.estimation_guidance) {
      sections.push(`## 📊 ESTIMATION GUIDANCE\n`);

      if (pbi.estimation_guidance.recommended_estimate) {
        sections.push(`**Recommended Estimate**: ${pbi.estimation_guidance.recommended_estimate}`);
      }

      if (pbi.estimation_guidance.complexity_factors && pbi.estimation_guidance.complexity_factors.length > 0) {
        sections.push(`\n**Complexity Factors**:`);
        for (const factor of pbi.estimation_guidance.complexity_factors) {
          sections.push(`- ${factor}`);
        }
      }

      if (pbi.estimation_guidance.similar_work) {
        sections.push(`\n**Similar Work**: ${pbi.estimation_guidance.similar_work}`);
      }

      sections.push('');
    }

    // Sprint Readiness
    sections.push(`## 🎯 SPRINT READINESS\n`);
    sections.push(`**ETA**: ${pbi.sprint_readiness_eta}`);
    sections.push(`**Sprint Ready**: ${pbi.recommended_next_actions.sprint_ready ? 'Yes ✅' : 'No ❌'}`);

    if (pbi.recommended_next_actions.can_start) {
      sections.push(`**Can Start**: ${pbi.recommended_next_actions.can_start}`);
    }

    sections.push('');

    // Metadata
    sections.push(`---`);
    sections.push(`*Generated by Backlog Chef - Step 8: Final Output*`);

    return sections.join('\n');
  }

  formatSummary(input: ReadinessAssessmentInput): string {
    const sections: string[] = [];

    sections.push(`# 📊 BACKLOG READINESS SUMMARY\n`);

    // Statistics
    sections.push(`## Summary Statistics\n`);
    sections.push(`- **Total PBIs Assessed**: ${input.metadata.total_pbis}`);
    sections.push(`- **Ready for Sprint**: ${input.metadata.ready_count} (${this.percentage(input.metadata.ready_count, input.metadata.total_pbis)}%)`);
    sections.push(`- **Needs Refinement**: ${input.metadata.needs_refinement_count}`);
    sections.push(`- **Not Ready**: ${input.metadata.not_ready_count}`);
    sections.push(`- **Average Readiness Score**: ${input.metadata.average_readiness_score}/100\n`);

    // Breakdown by status
    sections.push(`## PBI Breakdown\n`);

    const ready = input.readiness_assessment.filter(p => p.readiness_status.includes('READY'));
    const needsRefinement = input.readiness_assessment.filter(p => p.readiness_status.includes('NEEDS REFINEMENT'));
    const notReady = input.readiness_assessment.filter(p => p.readiness_status.includes('NOT READY'));

    if (ready.length > 0) {
      sections.push(`### 🟢 Ready for Sprint (${ready.length})\n`);
      for (const pbi of ready) {
        sections.push(`- [[${pbi.pbi_id}]] ${pbi.title} (Score: ${pbi.readiness_score})`);
      }
      sections.push('');
    }

    if (needsRefinement.length > 0) {
      sections.push(`### 🟡 Needs Refinement (${needsRefinement.length})\n`);
      for (const pbi of needsRefinement) {
        sections.push(`- [[${pbi.pbi_id}]] ${pbi.title} (Score: ${pbi.readiness_score})`);
      }
      sections.push('');
    }

    if (notReady.length > 0) {
      sections.push(`### 🔴 Not Ready (${notReady.length})\n`);
      for (const pbi of notReady) {
        sections.push(`- [[${pbi.pbi_id}]] ${pbi.title} (Score: ${pbi.readiness_score})`);
      }
      sections.push('');
    }

    // Metadata
    sections.push(`---`);
    sections.push(`*Generated: ${new Date(input.metadata.generated_at).toLocaleString()}*`);
    sections.push(`*Model: ${input.metadata.model_used}*`);
    sections.push(`*Processing Time: ${(input.metadata.processing_duration_ms / 1000).toFixed(2)}s*`);
    if (input.metadata.total_api_cost) {
      sections.push(`*API Cost: $${input.metadata.total_api_cost.toFixed(6)}*`);
    }

    return sections.join('\n');
  }

  getFileExtension(): string {
    return '.md';
  }

  getName(): string {
    return 'Markdown (Obsidian)';
  }

  private formatCriterionName(id: string): string {
    return id
      .split('_')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  private percentage(value: number, total: number): number {
    return total > 0 ? Math.round((value / total) * 100) : 0;
  }
}
